// Code generated by protoc-gen-go. DO NOT EDIT.
// source: foo.proto

package foo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateFooRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFooRequest) Reset()         { *m = CreateFooRequest{} }
func (m *CreateFooRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFooRequest) ProtoMessage()    {}
func (*CreateFooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{0}
}

func (m *CreateFooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFooRequest.Unmarshal(m, b)
}
func (m *CreateFooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFooRequest.Marshal(b, m, deterministic)
}
func (m *CreateFooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFooRequest.Merge(m, src)
}
func (m *CreateFooRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFooRequest.Size(m)
}
func (m *CreateFooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFooRequest proto.InternalMessageInfo

func (m *CreateFooRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreateFooResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFooResponse) Reset()         { *m = CreateFooResponse{} }
func (m *CreateFooResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFooResponse) ProtoMessage()    {}
func (*CreateFooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{1}
}

func (m *CreateFooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFooResponse.Unmarshal(m, b)
}
func (m *CreateFooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFooResponse.Marshal(b, m, deterministic)
}
func (m *CreateFooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFooResponse.Merge(m, src)
}
func (m *CreateFooResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFooResponse.Size(m)
}
func (m *CreateFooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFooResponse proto.InternalMessageInfo

func (m *CreateFooResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FooResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooResponse) Reset()         { *m = FooResponse{} }
func (m *FooResponse) String() string { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()    {}
func (*FooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{2}
}

func (m *FooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooResponse.Unmarshal(m, b)
}
func (m *FooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooResponse.Marshal(b, m, deterministic)
}
func (m *FooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooResponse.Merge(m, src)
}
func (m *FooResponse) XXX_Size() int {
	return xxx_messageInfo_FooResponse.Size(m)
}
func (m *FooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FooResponse proto.InternalMessageInfo

func (m *FooResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FooResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type GetFooByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFooByIDRequest) Reset()         { *m = GetFooByIDRequest{} }
func (m *GetFooByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetFooByIDRequest) ProtoMessage()    {}
func (*GetFooByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{3}
}

func (m *GetFooByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFooByIDRequest.Unmarshal(m, b)
}
func (m *GetFooByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFooByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetFooByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFooByIDRequest.Merge(m, src)
}
func (m *GetFooByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetFooByIDRequest.Size(m)
}
func (m *GetFooByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFooByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFooByIDRequest proto.InternalMessageInfo

func (m *GetFooByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateFooRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFooRequest) Reset()         { *m = UpdateFooRequest{} }
func (m *UpdateFooRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFooRequest) ProtoMessage()    {}
func (*UpdateFooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{4}
}

func (m *UpdateFooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFooRequest.Unmarshal(m, b)
}
func (m *UpdateFooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFooRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFooRequest.Merge(m, src)
}
func (m *UpdateFooRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFooRequest.Size(m)
}
func (m *UpdateFooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFooRequest proto.InternalMessageInfo

func (m *UpdateFooRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateFooRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UpdateFooResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFooResponse) Reset()         { *m = UpdateFooResponse{} }
func (m *UpdateFooResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFooResponse) ProtoMessage()    {}
func (*UpdateFooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{5}
}

func (m *UpdateFooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFooResponse.Unmarshal(m, b)
}
func (m *UpdateFooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFooResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFooResponse.Merge(m, src)
}
func (m *UpdateFooResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFooResponse.Size(m)
}
func (m *UpdateFooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFooResponse proto.InternalMessageInfo

func (m *UpdateFooResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFooRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFooRequest) Reset()         { *m = DeleteFooRequest{} }
func (m *DeleteFooRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFooRequest) ProtoMessage()    {}
func (*DeleteFooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{6}
}

func (m *DeleteFooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFooRequest.Unmarshal(m, b)
}
func (m *DeleteFooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFooRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFooRequest.Merge(m, src)
}
func (m *DeleteFooRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFooRequest.Size(m)
}
func (m *DeleteFooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFooRequest proto.InternalMessageInfo

func (m *DeleteFooRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFooResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFooResponse) Reset()         { *m = DeleteFooResponse{} }
func (m *DeleteFooResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFooResponse) ProtoMessage()    {}
func (*DeleteFooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ce1e2eec643ca48, []int{7}
}

func (m *DeleteFooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFooResponse.Unmarshal(m, b)
}
func (m *DeleteFooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFooResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFooResponse.Merge(m, src)
}
func (m *DeleteFooResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFooResponse.Size(m)
}
func (m *DeleteFooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFooResponse proto.InternalMessageInfo

func (m *DeleteFooResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateFooRequest)(nil), "github.com.hobord.goddd1.foo.CreateFooRequest")
	proto.RegisterType((*CreateFooResponse)(nil), "github.com.hobord.goddd1.foo.CreateFooResponse")
	proto.RegisterType((*FooResponse)(nil), "github.com.hobord.goddd1.foo.FooResponse")
	proto.RegisterType((*GetFooByIDRequest)(nil), "github.com.hobord.goddd1.foo.GetFooByIDRequest")
	proto.RegisterType((*UpdateFooRequest)(nil), "github.com.hobord.goddd1.foo.UpdateFooRequest")
	proto.RegisterType((*UpdateFooResponse)(nil), "github.com.hobord.goddd1.foo.UpdateFooResponse")
	proto.RegisterType((*DeleteFooRequest)(nil), "github.com.hobord.goddd1.foo.DeleteFooRequest")
	proto.RegisterType((*DeleteFooResponse)(nil), "github.com.hobord.goddd1.foo.DeleteFooResponse")
}

func init() { proto.RegisterFile("foo.proto", fileDescriptor_7ce1e2eec643ca48) }

var fileDescriptor_7ce1e2eec643ca48 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xbf, 0x4e, 0xc3, 0x30,
	0x18, 0xc4, 0xfb, 0x47, 0x45, 0xca, 0x87, 0x84, 0x82, 0xc5, 0x80, 0x2a, 0x06, 0x64, 0x96, 0xb2,
	0x18, 0x41, 0x17, 0xe6, 0x52, 0x05, 0xb1, 0x16, 0xb1, 0xb0, 0x91, 0xfa, 0x4b, 0x6b, 0x54, 0x72,
	0x21, 0x71, 0x91, 0x78, 0x43, 0x1e, 0x0b, 0x41, 0x20, 0x4d, 0x1d, 0x88, 0x3b, 0x46, 0x39, 0xff,
	0xee, 0x7c, 0x27, 0x53, 0x90, 0x00, 0x2a, 0xcb, 0x61, 0x21, 0x4e, 0x16, 0xc6, 0x2e, 0xd7, 0xb1,
	0x9a, 0xe3, 0x45, 0x2d, 0x11, 0x23, 0xd7, 0x6a, 0x01, 0xad, 0xf5, 0xa5, 0x4a, 0x00, 0x39, 0xa2,
	0xf0, 0x26, 0xe7, 0x27, 0xcb, 0x11, 0x30, 0xe3, 0xd7, 0x35, 0x17, 0x56, 0x1c, 0xd1, 0xc0, 0x1a,
	0xbb, 0xe2, 0xe3, 0xee, 0x69, 0x77, 0x14, 0xcc, 0xca, 0x0f, 0x79, 0x46, 0x87, 0x35, 0x65, 0x91,
	0x21, 0x2d, 0x58, 0x1c, 0x50, 0xcf, 0xe8, 0x1f, 0x5d, 0xcf, 0x68, 0x39, 0xa6, 0xfd, 0x96, 0xdf,
	0x1b, 0x72, 0xcf, 0x21, 0xdf, 0xb2, 0x8d, 0x80, 0xc9, 0xfb, 0xdd, 0xf4, 0x37, 0x84, 0x4b, 0xbe,
	0xa6, 0xf0, 0x21, 0xd3, 0xdb, 0x41, 0x77, 0xc6, 0xd7, 0x4e, 0xfe, 0x13, 0x5c, 0x52, 0x38, 0xe5,
	0x15, 0xb7, 0xe1, 0xbf, 0x40, 0x35, 0xcd, 0xdf, 0xa0, 0xab, 0x8f, 0x3e, 0x51, 0x04, 0xdc, 0x73,
	0xfe, 0x66, 0xe6, 0x2c, 0x52, 0x0a, 0xaa, 0xd6, 0x84, 0x52, 0x6d, 0x5b, 0x28, 0x77, 0x88, 0xe1,
	0xc5, 0xce, 0xfa, 0x32, 0x8c, 0xec, 0x88, 0x67, 0xa2, 0x4d, 0x97, 0xc2, 0x03, 0x68, 0xb4, 0x3e,
	0x3c, 0x6f, 0x3f, 0xb0, 0xed, 0x95, 0x52, 0x50, 0x15, 0xeb, 0xbb, 0x9b, 0xbb, 0x9d, 0xef, 0x6e,
	0x8d, 0xc5, 0x4a, 0xbf, 0xaa, 0x7f, 0x9f, 0x9f, 0x3b, 0xa6, 0xcf, 0xaf, 0x31, 0xac, 0xec, 0x4c,
	0x06, 0x8f, 0xfd, 0x04, 0x88, 0xf7, 0xbe, 0xdf, 0xd1, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf7,
	0x8b, 0x4f, 0x3e, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FooServiceClient is the client API for FooService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FooServiceClient interface {
	CreateFoo(ctx context.Context, in *CreateFooRequest, opts ...grpc.CallOption) (*CreateFooResponse, error)
	GetFooByID(ctx context.Context, in *GetFooByIDRequest, opts ...grpc.CallOption) (*FooResponse, error)
	UpdateFoo(ctx context.Context, in *UpdateFooRequest, opts ...grpc.CallOption) (*UpdateFooResponse, error)
	DeleteFoo(ctx context.Context, in *DeleteFooRequest, opts ...grpc.CallOption) (*DeleteFooResponse, error)
}

type fooServiceClient struct {
	cc *grpc.ClientConn
}

func NewFooServiceClient(cc *grpc.ClientConn) FooServiceClient {
	return &fooServiceClient{cc}
}

func (c *fooServiceClient) CreateFoo(ctx context.Context, in *CreateFooRequest, opts ...grpc.CallOption) (*CreateFooResponse, error) {
	out := new(CreateFooResponse)
	err := c.cc.Invoke(ctx, "/github.com.hobord.goddd1.foo.FooService/CreateFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) GetFooByID(ctx context.Context, in *GetFooByIDRequest, opts ...grpc.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := c.cc.Invoke(ctx, "/github.com.hobord.goddd1.foo.FooService/GetFooByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) UpdateFoo(ctx context.Context, in *UpdateFooRequest, opts ...grpc.CallOption) (*UpdateFooResponse, error) {
	out := new(UpdateFooResponse)
	err := c.cc.Invoke(ctx, "/github.com.hobord.goddd1.foo.FooService/UpdateFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) DeleteFoo(ctx context.Context, in *DeleteFooRequest, opts ...grpc.CallOption) (*DeleteFooResponse, error) {
	out := new(DeleteFooResponse)
	err := c.cc.Invoke(ctx, "/github.com.hobord.goddd1.foo.FooService/DeleteFoo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooServiceServer is the server API for FooService service.
type FooServiceServer interface {
	CreateFoo(context.Context, *CreateFooRequest) (*CreateFooResponse, error)
	GetFooByID(context.Context, *GetFooByIDRequest) (*FooResponse, error)
	UpdateFoo(context.Context, *UpdateFooRequest) (*UpdateFooResponse, error)
	DeleteFoo(context.Context, *DeleteFooRequest) (*DeleteFooResponse, error)
}

// UnimplementedFooServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFooServiceServer struct {
}

func (*UnimplementedFooServiceServer) CreateFoo(ctx context.Context, req *CreateFooRequest) (*CreateFooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFoo not implemented")
}
func (*UnimplementedFooServiceServer) GetFooByID(ctx context.Context, req *GetFooByIDRequest) (*FooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFooByID not implemented")
}
func (*UnimplementedFooServiceServer) UpdateFoo(ctx context.Context, req *UpdateFooRequest) (*UpdateFooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFoo not implemented")
}
func (*UnimplementedFooServiceServer) DeleteFoo(ctx context.Context, req *DeleteFooRequest) (*DeleteFooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFoo not implemented")
}

func RegisterFooServiceServer(s *grpc.Server, srv FooServiceServer) {
	s.RegisterService(&_FooService_serviceDesc, srv)
}

func _FooService_CreateFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).CreateFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hobord.goddd1.foo.FooService/CreateFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).CreateFoo(ctx, req.(*CreateFooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_GetFooByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFooByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).GetFooByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hobord.goddd1.foo.FooService/GetFooByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).GetFooByID(ctx, req.(*GetFooByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_UpdateFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).UpdateFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hobord.goddd1.foo.FooService/UpdateFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).UpdateFoo(ctx, req.(*UpdateFooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_DeleteFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).DeleteFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hobord.goddd1.foo.FooService/DeleteFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).DeleteFoo(ctx, req.(*DeleteFooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FooService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.hobord.goddd1.foo.FooService",
	HandlerType: (*FooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFoo",
			Handler:    _FooService_CreateFoo_Handler,
		},
		{
			MethodName: "GetFooByID",
			Handler:    _FooService_GetFooByID_Handler,
		},
		{
			MethodName: "UpdateFoo",
			Handler:    _FooService_UpdateFoo_Handler,
		},
		{
			MethodName: "DeleteFoo",
			Handler:    _FooService_DeleteFoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foo.proto",
}
