// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entities "github.com/hobord/goddd1/domain/entity"
import mock "github.com/stretchr/testify/mock"

// FooEntityRepository is an autogenerated mock type for the FooEntityRepository type
type FooEntityRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *FooEntityRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *FooEntityRepository) GetAll(ctx context.Context) ([]*entities.FooEntity, error) {
	ret := _m.Called(ctx)

	var r0 []*entities.FooEntity
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.FooEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.FooEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *FooEntityRepository) GetByID(ctx context.Context, id string) (*entities.FooEntity, error) {
	ret := _m.Called(ctx, id)

	var r0 *entities.FooEntity
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.FooEntity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.FooEntity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, entity
func (_m *FooEntityRepository) Save(ctx context.Context, entity *entities.FooEntity) error {
	ret := _m.Called(ctx, entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.FooEntity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
